name: Test CI/CD

# Trigger the workflow on push to any feature branch and on PRs to the development branch
on:
  pull_request:
    branches:
      - development  # Triggers on pull requests targeting the development branch
  workflow_run:
    workflows: ["Test CI/CD"]
    types:
      - completed  # Ensures this workflow runs when the Test CI/CD workflow is completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Run unit tests
        run: npm test -- --coverage

      - name: Build project
        run: npm run build
