name: Test CI/CD

# Trigger the workflow on push to any feature branch and on PRs to the development branch
on:
  push:
    branches:
      - 'feature-*'  # Triggers on branches with names starting with "feature-"
  pull_request:
    branches:
      - development  # Triggers on pull requests targeting the development branch

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment with the specified version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Lint the code to check for syntax and style issues
      - name: Lint code
        run: npm run lint

      # Run unit tests and generate coverage report
      - name: Run unit tests
        run: npm test -- --coverage

      # Build the project
      - name: Build project
        run: npm run build

      # Debug Git Information
      - name: Debug Git Information
        run: |
          git branch -a
          git remote -v
          git log --oneline -5
          echo "HEAD_BRANCH: feature-button"
          echo "BASE_BRANCH: development"

      # Create a pull request to the 'development' branch from the 'feature-button' branch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GIT_TOKEN }}
          branch: feature-button  # The source branch (your feature branch)
          base: development       # The target branch (your development branch)
          title: "Auto PR from feature-button"
          body: "This PR was automatically generated from feature-button."
          commit-message: "Auto commit message"
          delete-branch: false    # Optionally, do not delete the feature branch
