name: Deploy to Production

on:
  pull_request:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_IP: ${{ secrets.EC2_IP }}  # Store your EC2 IP in secrets
        run: |
          # Save the SSH key to a file
          echo "$EC2_SSH_KEY" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa

          # Use SSH to deploy to EC2
          ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no ubuntu@$EC2_IP << 'EOF'
            # Define the project directory
            PROJECT_DIR="/var/www/html/git_action_ci_cd"
            
            # Check if the project directory exists
            if [ ! -d "$PROJECT_DIR" ]; then
              echo "Creating project directory: $PROJECT_DIR"
              sudo mkdir -p $PROJECT_DIR
              sudo chown -R ubuntu:www-data $PROJECT_DIR
              sudo chmod -R 775 $PROJECT_DIR
            else
              echo "Project directory already exists: $PROJECT_DIR"
            fi
            
            # Navigate to the project directory
            cd $PROJECT_DIR
            
            # Initialize git if it doesn't exist and pull the latest code
            if [ ! -d ".git" ]; then
              echo "Initializing git repository..."
              git init
              git remote add origin https://github.com/zishan07cse/Git-Action-CI-CD.git
            fi
            
            # Fetch the latest code
            git fetch origin
            git reset --hard origin/production
            
            # Install dependencies and create a build
            if [ -f "package.json" ]; then
              npm install
              npm run build
            fi

            # Restart Apache or any other service
            sudo systemctl restart apache2

            echo "Deployment completed successfully."
          EOF
