name: Test CI/CD

# Trigger the workflow on push to any feature branch and on PRs to the dev branch
on:
  push:
    branches:
      - 'feature-*'  # Triggers on branches with names starting with "feature-"
  pull_request:
    branches:
      - dev  # Triggers on pull requests targeting the dev branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment with the specified version
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Lint the code to check for syntax and style issues
      - name: Lint code
        run: npm run lint

      # Run unit tests and generate coverage report
      - name: Run unit tests
        run: npm test -- --coverage

      # Build the project
      - name: Build project
        run: npm run build

      # Start the application (useful for feature testing)
      - name: Start the app
        run: npm start &
        env:
          CI: true  # Ensure Cypress runs in CI mode

      # Install Cypress (for feature testing)
     # - name: Install Cypress
      #  run: npm install cypress --save-dev

      # Run Cypress feature tests
      - name: Run Cypress feature tests
        run: npx cypress run
